AllCops:
  TargetRubyVersion: 2.2

ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

LineLength:
  Max: 170

MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

MethodLength:
  Max: 30

Semicolon:
  Enabled: false

EndOfLine:
  Enabled: false

TrailingBlankLines:
  Enabled: false